In [9]:
import pandas as pd
df_raw = pd.read_csv('../data/survey.csv')
df = df_raw.copy()
df.head()

,Record ID,Site,Cohort Year,DOB,Race,Please explain,Gender,Are you a U.S. Citizen or do you have a green card and permanent resident status?,"If not a U.S. Citizen or green card holder, are you an international student on a student visa or a DACA student?",Do you consider yourself coming from an economically or environmentally disadvantaged background?,...,7,8,9,10,11,12,13,14,15,16
0,4281-1,Moscow,2019-2021,34912.0,White.,NaN,Female,Yes,NaN,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000001,Seattle/Olympia,2019-2021,34219.0,Asian,NaN,Male,NaN,NaN,Yes,...,,,,,,,,,,
2,1000002,Seattle/Olympia,2019-2021,29809.0,Black or African American,NaN,Male,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000003,Seattle/Olympia,2019-2021,34215.0,Native Hawaiian or Other Pacific Islander. <sp...,NaN,Female,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000005,Spokane,2019-2021,34417.0,Other,NaN,Female,NaN,NaN,No,...,,,,,,,,,,

In [ ]:
# I want to combine two existing colums '
#"Are you a U.S. Citizen or do you have a green card and permanent resident status?" and "If not a U.S. Citizen or green card holder, are you an international student on a student visa or a DACA student? "
#into  one column, with 3 standardized answer options 1) green card/pr 2) daca or international student 3) other
# to do this, any "yes" answers in the first exist column map to answer 1. any no's in the first followed by a yes in the second map to standardized answer 2. otherwise, 3. 
#In the end, I want this new column to exist, and neither of the earlier two. what would the code for making these changes look like?

# Original column names (shortened for readability in the code)
col_citizen = "Are you a U.S. Citizen or do you have a green card and permanent resident status?"
col_visa = "If not a U.S. Citizen or green card holder, are you an international student on a student visa or a DACA student? "

def classify_citizenship(row):
    citizen_ans = str(row[col_citizen]).strip().lower()
    visa_ans = str(row[col_visa]).strip().lower()

    if citizen_ans == 'yes':
        return 'green card/pr'
    elif (not (citizen_ans == 'yes')  )and( visa_ans == 'yes'):
        return 'daca or international student'
    elif (not (citizen_ans == 'yes')) and (visa_ans == 'no'): 
        return'other'
    else:
        return 'NaN'

# Create new column
df['citizenship_status'] = df.apply(classify_citizenship, axis=1)

# Drop the original two columns
df = df.drop(columns=[col_citizen, col_visa])

# Verify the result
#print(df['citizenship_status'].value_counts())

df.head()

,Record ID,Site,Cohort Year,DOB,Race,Please explain,Gender,Do you consider yourself coming from an economically or environmentally disadvantaged background?,Are you the first person in your family to attend college?,"Does your father, mother, or spouse (or the previous employment, if no longer working or deceased) work in healthcare?",...,8,9,10,11,12,13,14,15,16,citizenship_status
0,4281-1,Moscow,2019-2021,34912.0,White.,NaN,Female,No,Yes,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,green card/pr
1,1000001,Seattle/Olympia,2019-2021,34219.0,Asian,NaN,Male,Yes,No,No,...,,,,,,,,,,NaN
2,1000002,Seattle/Olympia,2019-2021,29809.0,Black or African American,NaN,Male,Yes,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000003,Seattle/Olympia,2019-2021,34215.0,Native Hawaiian or Other Pacific Islander. <sp...,NaN,Female,Yes,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000005,Spokane,2019-2021,34417.0,Other,NaN,Female,No,No,No,...,,,,,,,,,,NaN